// Generated by extendr: Do not edit by hand
fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Relative to seurust/src/ (cargo cwd during R CMD INSTALL).
    let wrapper_path = "../R/extendr-wrappers.R";
    let header = "\
# Generated by extendr: Do not edit by hand\n\
# nolint start\n\
\n\
#' @docType package\n\
#' @usage NULL\n\
#' @useDynLib seurust, .registration = TRUE\n\
NULL\n\
\n\
";
    let footer = "# nolint end\n";
    let wrappers = seurust::get_seurust_metadata()
        .make_r_wrappers(true, "seurust")
        .map_err(|e| format!("failed to generate wrappers: {e}"))?;
    std::fs::write(wrapper_path, format!("{header}{wrappers}{footer}"))
        .map_err(|e| format!("failed to write {wrapper_path}: {e}"))?;
    Ok(())
}
