#!/usr/bin/env Rscript
system2("Rscript", "docker/scripts/bootstrap-dev-env.R", stdout = "", stderr = "")
source("examples/helpers/scrna_common.R", local = TRUE)
bootstrap_example_env()
set.seed(42)
counts <- simulate_scrna_counts(2500, 2000, 42)
seu <- CreateSeuratObject(counts, min.cells = 3, min.features = 50)
mat <- GetAssayData(seu, layer = "data")
mat <- Seurat:::LogNorm(GetAssayData(seu, layer = "counts"), 1e4, FALSE)
mu <- Matrix::rowMeans(mat)
cpp_var <- Seurat:::SparseRowVar2(mat, mu, FALSE)
rust_var <- seurust::SparseRowVar2(mat, mu, FALSE)
cat("var2 max diff:", max(abs(cpp_var - rust_var)), "\n")
cat("var2 all.equal:", isTRUE(all.equal(cpp_var, rust_var)), "\n")
