# Generated by extendr: Do not edit by hand
# nolint start
# Public wrappers for a subset of these entry points live in R/native.R.

log_norm <- function(x, i, p, nrows, ncols, scale_factor, display_progress) .Call(wrap__log_norm, x, i, p, nrows, ncols, scale_factor, display_progress)

standardize <- function(mat, display_progress) .Call(wrap__standardize, mat, display_progress)

fast_cov <- function(mat, center) .Call(wrap__fast_cov, mat, center)

fast_cov_mats <- function(mat1, mat2, center) .Call(wrap__fast_cov_mats, mat1, mat2, center)

fast_rbind <- function(mat1, mat2) .Call(wrap__fast_rbind, mat1, mat2)

row_var <- function(mat) .Call(wrap__row_var, mat)

fast_exp_mean <- function(x, i, p, nrows, ncols, display_progress) .Call(wrap__fast_exp_mean, x, i, p, nrows, ncols, display_progress)

sparse_row_var <- function(x, i, p, nrows, ncols, display_progress) .Call(wrap__sparse_row_var, x, i, p, nrows, ncols, display_progress)

sparse_row_var2 <- function(x, i, p, nrows, ncols, mu, display_progress) .Call(wrap__sparse_row_var2, x, i, p, nrows, ncols, mu, display_progress)

sparse_row_var_std <- function(x, i, p, nrows, ncols, mu, sd, vmax, display_progress) .Call(wrap__sparse_row_var_std, x, i, p, nrows, ncols, mu, sd, vmax, display_progress)

fast_log_vmr <- function(x, i, p, nrows, ncols, display_progress) .Call(wrap__fast_log_vmr, x, i, p, nrows, ncols, display_progress)

fast_sparse_row_scale <- function(x, i, p, nrows, ncols, scale, center, scale_max, display_progress) .Call(wrap__fast_sparse_row_scale, x, i, p, nrows, ncols, scale, center, scale_max, display_progress)

fast_sparse_row_scale_with_known_stats <- function(x, i, p, nrows, ncols, mu, sigma, scale, center, scale_max, display_progress) .Call(wrap__fast_sparse_row_scale_with_known_stats, x, i, p, nrows, ncols, mu, sigma, scale, center, scale_max, display_progress)

run_umi_sampling <- function(x, i, p, nrows, ncols, sample_val, upsample, `_display_progress`) .Call(wrap__run_umi_sampling, x, i, p, nrows, ncols, sample_val, upsample, `_display_progress`)

run_umi_sampling_per_cell <- function(x, i, p, nrows, ncols, sample_val, upsample, `_display_progress`) .Call(wrap__run_umi_sampling_per_cell, x, i, p, nrows, ncols, sample_val, upsample, `_display_progress`)

row_merge_matrices <- function(x1, j1, p1, nrows1, ncols1, x2, j2, p2, nrows2, ncols2, mat1_rownames, mat2_rownames, all_rownames) .Call(wrap__row_merge_matrices, x1, j1, p1, nrows1, ncols1, x2, j2, p2, nrows2, ncols2, mat1_rownames, mat2_rownames, all_rownames)

replace_cols <- function(x, i, p, nrows, ncols, col_idx, rx, ri, rp, rnrows, rncols) .Call(wrap__replace_cols, x, i, p, nrows, ncols, col_idx, rx, ri, rp, rnrows, rncols)

graph_to_neighbor_helper <- function(x, i, p, nrows, ncols) .Call(wrap__graph_to_neighbor_helper, x, i, p, nrows, ncols)

find_weights <- function(cells2, distances, anchor_cells2, integration_matrix_rownames, cell_index, anchor_score, min_dist, sd, display_progress) .Call(wrap__find_weights, cells2, distances, anchor_cells2, integration_matrix_rownames, cell_index, anchor_score, min_dist, sd, display_progress)

integrate_data <- function(ix, ii, ip, inrows, incols, wx, wi, wp, wnrows, wncols, ex, ei, ep, enrows, encols) .Call(wrap__integrate_data, ix, ii, ip, inrows, incols, wx, wi, wp, wnrows, wncols, ex, ei, ep, enrows, encols)

score_helper <- function(x, i, p, nrows, ncols, query_pca, query_dists, corrected_nns, k_snn, subtract_first_nn, display_progress) .Call(wrap__score_helper, x, i, p, nrows, ncols, query_pca, query_dists, corrected_nns, k_snn, subtract_first_nn, display_progress)

compute_snn <- function(nn_ranked, prune) .Call(wrap__compute_snn, nn_ranked, prune)

write_edge_file <- function(x, i, p, nrows, ncols, filename, display_progress) .Call(wrap__write_edge_file, x, i, p, nrows, ncols, filename, display_progress)

direct_snn_to_file <- function(nn_ranked, prune, display_progress, filename) .Call(wrap__direct_snn_to_file, nn_ranked, prune, display_progress, filename)

snn_smallest_nonzero_dist <- function(x, i, p, nrows, ncols, mat, n, nearest_dist) .Call(wrap__snn_smallest_nonzero_dist, x, i, p, nrows, ncols, mat, n, nearest_dist)

run_modularity_clustering <- function(x, i, p, nrows, ncols, modularity_function, resolution, algorithm, n_random_starts, n_iterations, random_seed, print_output, edgefilename) .Call(wrap__run_modularity_clustering, x, i, p, nrows, ncols, modularity_function, resolution, algorithm, n_random_starts, n_iterations, random_seed, print_output, edgefilename)

# nolint end
